FROM nginx
MAINTAINER JeriChen<jeri.chen0110@gmail.com>

ENV TZ=Asia/Taipei

RUN apt-get update; apt-get install -y openssl; apt-get install -y vim

ADD ./nginx.conf /etc/nginx/

RUN rm /etc/nginx/conf.d/default.conf

COPY ./scripts/hello.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/hello.sh
RUN /usr/local/bin/hello.sh

# ENTRYPOINT ["/usr/local/bin/hello.sh"]
# CMD ["nginx", "-g", "daemon on;"]
 
